### ISSUE TITLE
The train/val/test_iter in datasets.py

### ISSUE THREAD

**Issue by Apocalypse2403** [PRBonn/point-cloud-prediction#7]
Hi Benemer,

I have a question about the effect of train/val/test_iter in datasets.py, line 56, 67 and 78, what are they used for？

![iter](https://user-images.githubusercontent.com/49421307/172173165-d9f48f6a-160e-4d42-ac07-8c9db08b3922.png)

I’m running a network based on your code on multi gpus, but I met some errors about multi processed. If I commented out the train/val/test_iter the code will run without error, but I'm not sure whether commenting out them is correct or not.

Thanks!

**Comment by benemer** [comment]
Hi @Apocalypse2403,

the iterators can be used to iterate through the dataset, check out [this](https://pytorch.org/tutorials/beginner/basics/data_tutorial.html#iterate-through-the-dataloader) tutorial for further information.

Since this is already handled by Pytorch Lightning, we do not really need them. You can safely remove them.

I never tried running the code with multiple GPUs, therefore I can not provide further support here.

Best regards
Benedikt

**Comment by 3bobo** [comment]
hi, have you solved this? I also meet the same problem when using multiple GPUs in training

**Comment by benemer** [comment]
Have you tried removing the iterators as suggested by @Apocalypse2403?
